### PR TITLE
Simplify Geometry for Plotly 

### PR DESCRIPTION
**Pull request by trevorb1**
In this PR I have: 

- Added a simplify geometry function to the excluded regions html map to make the performance a little better.

### CODE REVIEW

**Comment by trevorb1** [comment]
@amanmajid Not a perfect solution, but here is my attempt to address the issue described in the readme! It def makes it a little snappier on my computer. Im fine if this doesnt cut it though and you still want switch to default presents :)

**Comment by amanmajid** [comment]
Hi @trevorb1 

Thanks for this also. 

This is very useful, but how computationally expensive is the `simplify_polygon` function? Using the plotly presets approach is quick and produces lightweight HTML outputs.

**Comment by trevorb1** [comment]
@amanmajid compared to the current implementation, a little bit longer (this is 100 runs on just the figure generation. ie. the `map_excluded_regions(...)` function) 

image

For the plotly presets, I wasnt sure if you meant basically removing the `update_layout` options?

**Comment by amanmajid** [comment]
Hi @trevorb1 - I've just refactored the `map_excluded_regions` plot to use plotly's default geometries (see [here](https://github.com/Electricity-Transmission-Database/electricity-transmission-database/commit/51fe41e2b42df176d6fca7d146c05bf68ef095c8)). This is a more minimal solution than doing a geom simplify within the plotting function so closing this for now.

**Pull request closed without merging**
