### PR TITLE
Fix North America Representation 

### PR DESCRIPTION
**Pull request by trevorb1**
In this PR I have: 
- Corrected naming of USA balancing authorities 
- Removed old USA and Canada regions from mapping files 
- Add balancing authorities to spatial representation

### CODE REVIEW

**Comment by trevorb1** [comment]
The renaming removes leftover nodes such as these ones: 
image

**Comment by trevorb1** [comment]
For adding the BAs to the spatial representation, I slightly tweaked the plotting so both the country and region are shown on the hoverboard. See below for example. This makes it a little funny for countries that do not have subregions, but I thought it was fine. I am happy to revert to the old hoverboard descriptions tho! :) 

Screenshot 2023-12-12 182859

Screenshot 2023-12-12 183820

**Comment by trevorb1** [comment]
For review: 
- @maartenbrinkerink can you please do a quick sanity check on the CSV files that the USA and CAN regions I removed are in fact carry overs from an old spatial representation 
- @amanmajid are you okay with my implementation of pulling in the USA data? I tried to just copy your code as much as possible :)

**Comment by amanmajid** [comment]
Hi @trevorb1. Thanks for your edits! This is all looking great so I will merge the PR.

**Pull request merged**
